// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaT8QL7fmZlmA1sXyZzHwYHFa9qH4EtXU',
    appId: '1:452951105699:web:5b3c89c479d209d77adf16',
    messagingSenderId: '452951105699',
    projectId: 'redifit-5b503',
    authDomain: 'redifit-5b503.firebaseapp.com',
    storageBucket: 'redifit-5b503.appspot.com',
    measurementId: 'G-1YYBY8VSR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKLCqkOoAy3B3gzkclwTER4nIr_bzuZ0g',
    appId: '1:452951105699:android:cc73865fe4ed4cae7adf16',
    messagingSenderId: '452951105699',
    projectId: 'redifit-5b503',
    storageBucket: 'redifit-5b503.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5GHbNdJMdH56naM7DWwmlYWVVTOmWp1o',
    appId: '1:452951105699:ios:e10eb767f12e50417adf16',
    messagingSenderId: '452951105699',
    projectId: 'redifit-5b503',
    storageBucket: 'redifit-5b503.appspot.com',
    iosClientId: '452951105699-go5rkrm8f5k1s0cco6b94lkdfl93p37o.apps.googleusercontent.com',
    iosBundleId: 'com.nutrition.redifit',
  );
}
